### ISSUE TITLE
Colaboración con Asociacion Lúdico cultural Íñigo Montoya

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/evento2016#1]
Entiendo por [esta conversación del Grupo de Miembros Activos](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/miembros-activos-asrob/1s7bTw7jO8A/7fqz1P8rAwAJ) que que @David-Estevez se está encargando de esto... Todo en orden, ¿correcto?

**Comment by David-Estevez** [comment]
Estoy trabajando en ello, sí, la semana que viene me paso a hablar con ellos y concretar los detalles.

**Comment by jgvictores** [comment]
Bien! Thanks!
