### ISSUE TITLE
Información sobre el hackatón

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/evento2016#15]
La gente lee que hay un hackatón, pero no sabe ni de qué, ni cómo, ni ná. Hace falta poner al menos un párrafo de información sobre el hackatón en la sección correspondiente.

**Comment by JorFru** [comment]
## Es mi cometido!

**Comment by JorFru** [comment]
Vale!
Pero, para empezar, habría que hacer el siguiente gran cambio.
Ahora hay una sessión que se llama "más"

Yo haría una sección de Hackatón y otra de juegos con Íñigo Montoya

Por ahora voy a modificar "más" y pondré sólo la información del hackatón
Cuando se abra la nueva sección escribiré lo de Íñigo Montoya

Y si no os parece bien hacerlo así separado, pues se discute

**Comment by jgvictores** [comment]
A mí, estéticamente, no me molesta que estén en la sección "más". En "talleres" hay varios talleres que conviven felizmente, y lo mismo ocurre con "charlas".
De todos modos, si lo crees conveniente y los cambios no rompen la página demasiado... ¡adelante!

**Comment by JorFru** [comment]
Vale!
Pero molaría que el hackatón saliese en el menú de arriba

Entonces pondré

# Hackatón

bastante en grande, aunque dentro de la sección "más"

**Comment by jgvictores** [comment]
Quedando juegos con Íñigo Montoya como...

# Juegos

??? :face_with_head_bandage:

**Comment by JorFru** [comment]
Tampoco hace falta que el hackatón monopolice todo, pero vistoso debería de quedar

**Comment by KFRodicio** [comment]
Yo opino como jorge, el Hackaton debería tener mucha visibilidad, yo igual
lo pondría también como sección a parte

**Comment by jgvictores** [comment]
Ok, el tema del nombre la sección de Juegos Con Montoya queda pendiente para #17.

**Comment by David-Estevez** [comment]
A mi tampoco me disgusta que ambas cosas compartan sección en "Más".  No creo que el contenido de cada una de ellas individualmente vaya a dar como para llenar una sección, no?

**Comment by jgvictores** [comment]
Poniendo JUEGOS antes que HACKATON puede quedar ok:
`HOME PROGRAMA CHARLAS TALLERES JUEGOS HACKATON ¿DONDE? ¡INSCRIBETE!`

**Comment by jgvictores** [comment]
> Poniendo JUEGOS antes que HACKATON puede quedar ok:
> `HOME PROGRAMA CHARLAS TALLERES JUEGOS HACKATON ¿DONDE? ¡INSCRIBETE!`

O por lo menos me parecería un orden lógico. ¿Vosotros qué opináis?

**Comment by JorFru** [comment]
A mí me parece que lo que dice Juan tiene buen visibilidad
Y los cambios que habría que hacer no son muy complicados

**Comment by David-Estevez** [comment]
Si metemos muchas cosas la barra superior se peta de cosas. No sé qué tal se verá eso en móvil.

**Comment by JorFru** [comment]
En el móvil se verá bien
Ahora tiene dos filas: cuatro arriba y tres abajo.
Con el cambio se pondrán cuatro arriba y cuatro abajo.
La movida será si ponemos 9 secciones...

**Comment by JorFru** [comment]
A mí me parece que lo que dice Juan tiene buen visibilidad
Y los cambios que habría que hacer no son muy complicados

**Comment by JorFru** [comment]
![captura](https://cloud.githubusercontent.com/assets/11017088/19318413/e74e26aa-90a8-11e6-92a9-32051bf0a317.JPG)

Sugiero el siguiente cambio de paleta de colores
He añadido un color nuevo para la sección nueva que ocupará el hackatón. Ahora son ocho, y en el móvil se visualizarán bien.
He cambiado un poco el color verde, que parecía fluorescente.
El rosa y rojo es de http://smartdatahack.org/ , y el morado me lo he inventado.

Echadle un ojo a ver qué os parece

**Comment by JorFru** [comment]
Ya está terminado.
A lo de los colores le he dado muchas vueltas, y además cada pantalla es un mundo, a si que he dejado algo que se ve lo mejor posible en cualquier plataforma y no cansa demasiado la vista con colores chillones.

Sugerencias por aquí, gracias
