### ISSUE TITLE
Revisar vulnerabilidades en dependencias

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/evento2016#34]
Revisar vulnerabilidades en dependencias.

No lo he descubierto yo, sino GitHub: https://github.com/asrob-uc3m/evento2016/network/dependencies
: )

**Comment by d-marcos-m** [comment]
Resuelto. En el primer commit que fixeaba la issue saltó un error de formato por un {% for %} no cerrado que sí estaba cerrado. Para resolverlo he añadido 'excerpt_separator: ""' al _config.yml.
